import Config

# For production, we often load configuration from external
# sources, such as your system environment. For this reason,
# you won't find the :http configuration below, but set inside
# JustWeb.Endpoint.init/2 when load_from_system_env is
# true. Any dynamic configuration should be done there.
#
# Don't forget to configure the url host to something meaningful,
# Phoenix uses this information when generating URLs.
#
# Finally, we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the mix phx.digest task
# which you typically run after static files are built.
config :phoenix, :serve_endpoints, true

if config_env() == :prod do
  config :just, Just.Repo,
    adapter: Ecto.Adapters.Postgres,
    pool_size: 10,
    queue_target: 1_000,
    url: System.fetch_env!("JUST_POSTGRESQL_URL"),
    ssl: true,
    timeout: 60_000,
    start_apps_before_migration: [:ssl],
    disconnect_on_error_codes: [:read_only_sql_transaction]

  config :just, JustWeb.Endpoint,
    http: [port: 4000],
    load_from_system_env: true,
    url: [scheme: "https", host: System.fetch_env!("JUST_SELF_HOST"), port: 443],
    secret_key_base: System.fetch_env!("JUST_PHOENIX_SECRET_KEY_BASE"),
    check_origin: [
      "//*.mydomain.com.br"
    ]
end
